<!DOCTYPE html>
<html lang="en-US" prefix="og: http://ogp.me/ns#">

<!-- Mirrored from beginnersbook.com/2013/05/catch-multiple-exceptions/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 16 Apr 2018 05:22:16 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head >
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>How to Catch multiple exceptions</title>

<!-- This site is optimized with the Yoast SEO plugin v7.0.3 - https://yoast.com/wordpress/plugins/seo/ -->
<meta name="description" content="In the previous tutorial, I have covered how to handle exceptions using try-catch blocks. In this guide, we will see how to handle multiple exceptions and how to write them in a correct order so that user gets a meaningful message for each type of exception. Catching multiple exceptions Lets take an example to"/>
<link rel="canonical" href="index.html" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="article" />
<meta property="og:title" content="How to Catch multiple exceptions" />
<meta property="og:description" content="In the previous tutorial, I have covered how to handle exceptions using try-catch blocks. In this guide, we will see how to handle multiple exceptions and how to write them in a correct order so that user gets a meaningful message for each type of exception. Catching multiple exceptions Lets take an example to" />
<meta property="og:url" content="index.html" />
<meta property="og:site_name" content="beginnersbook.com" />
<meta property="article:section" content="Exception Handling" />
<meta property="article:published_time" content="2013-05-13T19:16:19+00:00" />
<meta property="article:modified_time" content="2017-09-05T16:27:42+00:00" />
<meta property="og:updated_time" content="2017-09-05T16:27:42+00:00" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:description" content="In the previous tutorial, I have covered how to handle exceptions using try-catch blocks. In this guide, we will see how to handle multiple exceptions and how to write them in a correct order so that user gets a meaningful message for each type of exception. Catching multiple exceptions Lets take an example to" />
<meta name="twitter:title" content="How to Catch multiple exceptions" />
<!-- / Yoast SEO plugin. -->

<link rel='dns-prefetch' href='../../../index.html' />
<link rel='dns-prefetch' href='http://fonts.googleapis.com/' />
<link rel='dns-prefetch' href='http://s.w.org/' />
<link rel="alternate" type="application/rss+xml" title="beginnersbook.com &raquo; Feed" href="https://feeds.feedburner.com/BeginnersBookFeed" />
<link rel="alternate" type="application/rss+xml" title="beginnersbook.com &raquo; Comments Feed" href="../../../comments/feed/index.html" />
<link rel="alternate" type="application/rss+xml" title="beginnersbook.com &raquo; How to Catch multiple exceptions Comments Feed" href="feed/index.html" />
<link rel='stylesheet' id='news-pro-theme-css'  href='../../../wp-content/themes/news-pro/style3c43.css?ver=3.0.31' type='text/css' media='all' />
<link rel='stylesheet' id='google-fonts-css'  href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' type='text/css' media='all' />
<!--[if lt IE 9]>
<script type='text/javascript' src='https://beginnersbook.com/wp-content/themes/genesis/lib/js/html5shiv.min.js?ver=3.7.3'></script>
<![endif]-->
<script type='text/javascript' src='../../../wp-includes/js/jquery/jqueryb8ff.js?ver=1.12.4'></script>
<script type='text/javascript' src='../../../wp-includes/js/jquery/jquery-migrate.min330a.js?ver=1.4.1'></script>
<script type='text/javascript' src='../../../wp-content/themes/news-pro/js/responsive-menu8a54.js?ver=1.0.0'></script>
<link rel='https://api.w.org/' href='../../../wp-json/index.html' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="../../../xmlrpc0db0.html?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="../../../wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.9.5" />
<link rel='shortlink' href='../../../index5c59.html?p=2562' />
<link rel="alternate" type="application/json+oembed" href="../../../wp-json/oembed/1.0/embed2abe.json?url=https%3A%2F%2Fbeginnersbook.com%2F2013%2F05%2Fcatch-multiple-exceptions%2F" />
<link rel="alternate" type="text/xml+oembed" href="../../../wp-json/oembed/1.0/embed6517?url=https%3A%2F%2Fbeginnersbook.com%2F2013%2F05%2Fcatch-multiple-exceptions%2F&amp;format=xml" />
<script async src="../../../../pagead2.googlesyndication.com/pagead/js/f.txt"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1952308982289269",
    enable_page_level_ads: true
  });
</script><style type="text/css">.site-title a { background: url(../../../wp-content/uploads/2017/02/cropped-bbook_logo_17.png) no-repeat !important; }</style>
<link rel="icon" href="../../../wp-content/uploads/2016/03/favicon2.png" sizes="32x32" />
<link rel="icon" href="../../../wp-content/uploads/2016/03/favicon2.png" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="../../../wp-content/uploads/2016/03/favicon2.png" />
<meta name="msapplication-TileImage" content="https://beginnersbook.com/wp-content/uploads/2016/03/favicon2.png" />
</head>
<body class="post-template-default single single-post postid-2562 single-format-standard custom-header header-image header-full-width sidebar-content-sidebar news-pro-green" itemscope itemtype="https://schema.org/WebPage"><div class="site-container"><header class="site-header" itemscope itemtype="https://schema.org/WPHeader"><div class="wrap"></div></header><nav class="nav-primary" aria-label="Main" itemscope itemtype="https://schema.org/SiteNavigationElement"><div class="wrap"><ul id="menu-main-menu" class="menu genesis-nav-menu menu-primary"><li id="menu-item-6105" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-6105"><a href="../../../index.html" itemprop="url"><span itemprop="name">Home</span></a></li>
<li id="menu-item-5678" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5678"><a href="../../../java-tutorial-for-beginners-with-examples/index.html" itemprop="url"><span itemprop="name">Core Java</span></a></li>
<li id="menu-item-5682" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5682"><a href="../../04/oops-concepts/index.html" itemprop="url"><span itemprop="name">OOPs</span></a></li>
<li id="menu-item-6236" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6236"><a href="../../../java-collections-tutorials/index.html" itemprop="url"><span itemprop="name">Collections</span></a></li>
<li id="menu-item-6237" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6237"><a href="../../../java-io-tutorial-with-examples/index.html" itemprop="url"><span itemprop="name">Java I/O</span></a></li>
<li id="menu-item-6242" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6242"><a href="../../../2015/04/json-tutorial/index.html" itemprop="url"><span itemprop="name">JSON</span></a></li>
<li id="menu-item-5679" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5679"><a href="../../../jsp-tutorial-for-beginners/index.html" itemprop="url"><span itemprop="name">JSP</span></a></li>
<li id="menu-item-6235" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6235"><a href="../../../jsp-jstl-tutorial-jstl-functions-and-core-tags/index.html" itemprop="url"><span itemprop="name">JSTL</span></a></li>
<li id="menu-item-7076" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-7076"><a href="../servlet-tutorial/index.html" itemprop="url"><span itemprop="name">Servlet</span></a></li>
<li id="menu-item-6239" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6239"><a href="../../../2014/01/c-tutorial-for-beginners-with-examples/index.html" itemprop="url"><span itemprop="name">C Tutorial</span></a></li>
<li id="menu-item-6241" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6241"><a href="../../../2015/04/dbms-tutorial/index.html" itemprop="url"><span itemprop="name">DBMS</span></a></li>
<li id="menu-item-6243" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6243"><a href="../../../2017/02/perl-tutorial-for-beginners/index.html" itemprop="url"><span itemprop="name">Perl</span></a></li>
</ul></div></nav><div class="site-inner"><div class="content-sidebar-wrap"><main class="content"><article class="post-2562 post type-post status-publish format-standard category-exception-handling entry" itemscope itemtype="https://schema.org/CreativeWork"><header class="entry-header"><h1 class="entry-title" itemprop="headline">How to Catch multiple exceptions</h1>
<p class="entry-meta">By <span class="entry-author" itemprop="author" itemscope itemtype="https://schema.org/Person"><span class="entry-author-name" itemprop="name">Chaitanya Singh</span></span> | <span class="entry-categories">Filed Under: <a href="../../../category/technology/java-guide/exception-handling/index.html" rel="category tag">Exception Handling</a></span> </p><style type="text/css">
.bbook_responsive_top { display: block; width: 320px; height: 100px; margin: 15px auto; }
@media(min-width: 500px) { .bbook_responsive_top {  width: 300px; height: 250px; margin: 15px auto; } }
@media(min-width: 800px) { .bbook_responsive_top { margin: 15px auto; width: 728px; height: 90px; margin-left: 0; } }
</style>
<script async src="../../../../pagead2.googlesyndication.com/pagead/js/f.txt"></script>
<!-- bbook_top_center -->
<ins class="adsbygoogle bbook_responsive_top"
     style="display:block"
     data-ad-client="ca-pub-1952308982289269"
     data-ad-slot="3105487525"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</header><div class="entry-content" itemprop="text"><p>In the <a href="../../04/try-catch-in-java/index.html">previous tutorial</a>, I have covered how to handle exceptions using try-catch blocks. In this guide, we will see how to handle multiple exceptions and how to write them in a correct order so that user gets a meaningful message for each type of exception.</p>
<h2>Catching multiple exceptions</h2>
<p>Lets take an example to understand how to handle multiple exceptions.</p>
<pre>class Example{
   public static void main(String args[]){
      try{
         int arr[]=new int[7];
         arr[4]=30/0;
         System.out.println("Last Statement of try block");
      }
      catch(ArithmeticException e){
         System.out.println("You should not divide a number by zero");
      }
      catch(ArrayIndexOutOfBoundsException e){
         System.out.println("Accessing array elements outside of the limit");
      }
      catch(Exception e){
         System.out.println("Some Other Exception");
      }
      System.out.println("Out of the try-catch block");
   }
}</pre>
<p><strong>Output:</strong></p>
<pre>You should not divide a number by zero
Out of the try-catch block</pre>
<p>In the above example, the first catch block got executed because the code we have written in try block throws ArithmeticException (because we divided the number by zero).</p><div class="googlead"><script async src="../../../../pagead2.googlesyndication.com/pagead/js/f.txt"></script>
<ins class="adsbygoogle"
     style="display:block; text-align:center;"
     data-ad-format="fluid"
     data-ad-layout="in-article"
     data-ad-client="ca-pub-1952308982289269"
     data-ad-slot="7043774673"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script></div>
<p><strong>Now lets change the code a little bit and see the change in output:</strong></p>
<pre>class Example{
   public static void main(String args[]){
      try{
         int arr[]=new int[7];
         arr[10]=10/5;
         System.out.println("Last Statement of try block");
      }
      catch(ArithmeticException e){
         System.out.println("You should not divide a number by zero");
      }
      catch(ArrayIndexOutOfBoundsException e){
         System.out.println("Accessing array elements outside of the limit");
      }
      catch(Exception e){
         System.out.println("Some Other Exception");
      }
      System.out.println("Out of the try-catch block");
   }
}</pre>
<p>Output:</p>
<pre>Accessing array elements outside of the limit
Out of the try-catch block</pre>
<p>In this case, the second catch block got executed because the code throws ArrayIndexOutOfBoundsException. We are trying to access the 11th element of array in above program but the array size is only 7.</p>
<p><strong>What did we observe from the above two examples?</strong><br />
1. It is clear that when an exception occurs, the specific catch block (that declares that exception) executes. This is why in first example first block executed and in second example second catch.<br />
2. Although I have not shown you above, but if an exception occurs in above code which is not Arithmetic and ArrayIndexOutOfBounds then the last generic catch handler would execute.</p>
<p><strong>Lets change the code again and see the output:</strong></p>
<pre>class Example{
   public static void main(String args[]){
      try{
         int arr[]=new int[7];
         arr[10]=10/5;
         System.out.println("Last Statement of try block");
      }
      catch(Exception e){
         System.out.println("Some Other Exception");
      }
      catch(ArithmeticException e){
         System.out.println("You should not divide a number by zero");
      }
      catch(ArrayIndexOutOfBoundsException e){
         System.out.println("Accessing array elements outside of the limit");
      }
      System.out.println("Out of the try-catch block");
   }
}</pre>
<p><strong>Output:</strong></p>
<pre>Compile time error: Exception in thread "main" java.lang.Error: 
Unresolved compilation problems: Unreachable catch block for ArithmeticException.
It is already handled by the catch block for Exception Unreachable catch block 
for ArrayIndexOutOfBoundsException. It is already handled by the catch block for
Exception at Example.main(Example1.java:11)</pre>
<p><strong>Why we got this error?</strong><br />
This is because we placed the generic exception catch block at the first place which means that none of the catch blocks placed after this block is reachable. You should always place this block at the end of all other specific exception catch blocks.</p>
<div class="bb-nav"><a class="pretut" href="../../04/try-catch-in-java/index.html">❮ Previous</a><a class="nexttut" href="../../04/nested-try-catch/index.html">Next ❯</a></div>
</p></div><style>
.bbook_responsive_bottom { display: block; width: 300px; height: 250px; margin: 15px auto; }
@media(min-width: 800px) { .bbook_responsive_bottom { margin: 15px auto; width: 336px; height: 280px; margin-left: 0; } }
</style>
<script async src="../../../../pagead2.googlesyndication.com/pagead/js/f.txt"></script>
<!-- bbook_bottom_center -->
<ins class="adsbygoogle bbook_responsive_bottom"
     style="display:block"
     data-ad-client="ca-pub-1952308982289269"
     data-ad-slot="6278445773"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<footer class="entry-footer"></footer></article><div class="entry-comments" id="comments"><h3>Comments</h3><ol class="comment-list">
	<li class="comment even thread-even depth-1" id="comment-68900">
	<article itemprop="comment" itemscope itemtype="https://schema.org/Comment">

		
		<header class="comment-header">
			<p class="comment-author" itemprop="author" itemscope itemtype="https://schema.org/Person">
				<img alt='' src='https://secure.gravatar.com/avatar/eff6861ff8dee138c187f7265826bd10?s=48&amp;d=monsterid&amp;r=g' srcset='https://secure.gravatar.com/avatar/eff6861ff8dee138c187f7265826bd10?s=96&#038;d=monsterid&#038;r=g 2x' class='avatar avatar-48 photo' height='48' width='48' /><span itemprop="name">Abhishek Bharat Parab</span> <span class="says">says</span>			</p>

			<p class="comment-meta"><time class="comment-time" datetime="2017-03-25T10:50:44+00:00" itemprop="datePublished"><a href="index.html#comment-68900" class="comment-time-link" itemprop="url">March 25, 2017 at 10:50 AM</a></time></p>		</header>

		<div class="comment-content" itemprop="text">
			
			<p>Confusion about above example. If ArithmeticException, NullPointerException ArrayIndexOutOfBoundsException exception class are child of RuntimeExecption parent class, and these class is useful to handle runtime exception then why should it be followed by method declaration using throws keyword. since throws keyword is used to handle compile time exception.</p>
<p>Requesting your assistance for following queries :</p>
<p>1. If we can handle exceptions(checked/unchecked) using try/catch block, then why should we use throw or throws keyword in program with real time example?</p>
<p>2. Please tell me a situation where throw or throws keyword has to be used in program. please explain with an example </p>
<p>3. public void myMethod() throws ArithmeticException {<br />
       int division = 10/0 ;<br />
   step 1:    new throw ArithmeticException(&#8220;cannot be divided by zero&#8221;);</p>
<p>}</p>
<p>In this example, If arithmeticException class is used to handle runtime exception, so why do we use it followed by throws keyword in method declaration?<br />
does step 1 not sufficient to handle &#8220;divided by zero&#8221; exception?</p>
<p>I would be awaiting for your response respect to my queries</p>
		</div>

		<div class="comment-reply"><a rel='nofollow' class='comment-reply-link' href='#comment-68900' onclick='return addComment.moveForm( "comment-68900", "68900", "respond", "2562" )' aria-label='Reply to Abhishek Bharat Parab'>Reply</a></div>
		
	</article>
	<ul class="children">

	<li class="comment odd alt depth-2" id="comment-70187">
	<article itemprop="comment" itemscope itemtype="https://schema.org/Comment">

		
		<header class="comment-header">
			<p class="comment-author" itemprop="author" itemscope itemtype="https://schema.org/Person">
				<img alt='' src='https://secure.gravatar.com/avatar/c37c583372fb97fd753a7c32ee3c3b7d?s=48&amp;d=monsterid&amp;r=g' srcset='https://secure.gravatar.com/avatar/c37c583372fb97fd753a7c32ee3c3b7d?s=96&#038;d=monsterid&#038;r=g 2x' class='avatar avatar-48 photo' height='48' width='48' /><span itemprop="name">raghu</span> <span class="says">says</span>			</p>

			<p class="comment-meta"><time class="comment-time" datetime="2017-05-07T03:44:16+00:00" itemprop="datePublished"><a href="index.html#comment-70187" class="comment-time-link" itemprop="url">May 7, 2017 at 3:44 AM</a></time></p>		</header>

		<div class="comment-content" itemprop="text">
			
			<p>keyword throw is used to define pre-defined/user defined exceptions<br />
throws:<br />
Actually all the possible exceptions must be handled by using try and catch block if we are not interested to handle checked exceptions atleast we need to make JVM to handle the checked exceptions by using keyword &#8220;throws&#8221; otherwise jvm will rise compile time error<br />
throws is not exception handler it is an exception escaper.hence throws are not recommended in the industry programs which leads abnormal termination</p>
		</div>

		<div class="comment-reply"><a rel='nofollow' class='comment-reply-link' href='#comment-70187' onclick='return addComment.moveForm( "comment-70187", "70187", "respond", "2562" )' aria-label='Reply to raghu'>Reply</a></div>
		
	</article>
	</li><!-- #comment-## -->

	<li class="comment even depth-2" id="comment-72519">
	<article itemprop="comment" itemscope itemtype="https://schema.org/Comment">

		
		<header class="comment-header">
			<p class="comment-author" itemprop="author" itemscope itemtype="https://schema.org/Person">
				<img alt='' src='https://secure.gravatar.com/avatar/8d9761e9e3bc719ad37a4266d54640fb?s=48&amp;d=monsterid&amp;r=g' srcset='https://secure.gravatar.com/avatar/8d9761e9e3bc719ad37a4266d54640fb?s=96&#038;d=monsterid&#038;r=g 2x' class='avatar avatar-48 photo' height='48' width='48' /><span itemprop="name">Mithilesh Naik</span> <span class="says">says</span>			</p>

			<p class="comment-meta"><time class="comment-time" datetime="2017-07-23T16:15:04+00:00" itemprop="datePublished"><a href="index.html#comment-72519" class="comment-time-link" itemprop="url">July 23, 2017 at 4:15 PM</a></time></p>		</header>

		<div class="comment-content" itemprop="text">
			
			<p>Hi Abhishek,</p>
<p>Answer o 1) usually you will see operations like these:</p>
<p>classA.methodA calls classB.methodB which again calls classC.methodC</p>
<p>class C returns something all the way to class A<br />
  (Only class A is allowed to interact to user)</p>
<p>in this case if exception occurs in class C then you throw it using<br />
    throw new your-exception   //from code<br />
or add  &#8220;throws ExpectedException&#8221; in method signature of methodC</p>
<p>MethodC will throw it to methodB this should also have throws declaration. MethodB will throw it to methodA.</p>
<p>Method A will catch it in a catch block and do corresponding action</p>
<p>**This answers Q2**</p>
<p>Answer to 3)<br />
in case 10/0 you dont need to throw exception explicitly. However say, your operation cannot support divide by 5 (assume). in this case do following</p>
<p>if (divisor ==5)<br />
  throw OperationNotSupported or throw ArithmeticException</p>
		</div>

		<div class="comment-reply"><a rel='nofollow' class='comment-reply-link' href='#comment-72519' onclick='return addComment.moveForm( "comment-72519", "72519", "respond", "2562" )' aria-label='Reply to Mithilesh Naik'>Reply</a></div>
		
	</article>
	</li><!-- #comment-## -->
</ul><!-- .children -->
</li><!-- #comment-## -->
</ol></div>	<div id="respond" class="comment-respond">
		<h3 id="reply-title" class="comment-reply-title">Leave a Reply <small><a rel="nofollow" id="cancel-comment-reply-link" href="index.html#respond" style="display:none;">Cancel reply</a></small></h3>			<form action="https://beginnersbook.com/wp-comments-post.php" method="post" id="commentform" class="comment-form" novalidate>
				<p class="comment-notes"><span id="email-notes">Your email address will not be published.</span> Required fields are marked <span class="required">*</span></p><p class="comment-form-comment"><label for="comment">Comment</label> <textarea id="comment" name="comment" cols="45" rows="8" maxlength="65525" required="required"></textarea></p><p class="comment-form-author"><label for="author">Name <span class="required">*</span></label> <input id="author" name="author" type="text" value="" size="30" maxlength="245" required='required' /></p>
<p class="comment-form-email"><label for="email">Email <span class="required">*</span></label> <input id="email" name="email" type="email" value="" size="30" maxlength="100" aria-describedby="email-notes" required='required' /></p>
<p class="comment-form-url"><label for="url">Website</label> <input id="url" name="url" type="url" value="" size="30" maxlength="200" /></p>
<p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="Post Comment" /> <input type='hidden' name='comment_post_ID' value='2562' id='comment_post_ID' />
<input type='hidden' name='comment_parent' id='comment_parent' value='0' />
</p><p style="display: none;"><input type="hidden" id="akismet_comment_nonce" name="akismet_comment_nonce" value="8c41877057" /></p><p style="display: none;"><input type="hidden" id="ak_js" name="ak_js" value="228"/></p>			</form>
			</div><!-- #respond -->
	</main><aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar" itemscope itemtype="https://schema.org/WPSideBar"><section id="search-2" class="widget widget_search"><div class="widget-wrap"><form class="search-form" itemprop="potentialAction" itemscope itemtype="https://schema.org/SearchAction" method="get" action="https://beginnersbook.com/" role="search"><meta itemprop="target" content="../../../index1f8a.html?s={s}"/><input itemprop="query-input" type="search" name="s" placeholder="Search this website &#x2026;" /><input type="submit" value="Search"  /></form></div></section>
<section id="custom_html-2" class="widget_text widget widget_custom_html"><div class="widget_text widget-wrap"><div class="textwidget custom-html-widget"><script async src="../../../../pagead2.googlesyndication.com/pagead/js/f.txt"></script>
<!-- BB_Top_Responsive -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-1952308982289269"
     data-ad-slot="1008192093"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div></section>
<section id="custom_html-9" class="widget_text widget widget_custom_html"><div class="widget_text widget-wrap"><div class="textwidget custom-html-widget"><script async src="../../../../pagead2.googlesyndication.com/pagead/js/f.txt"></script>
<!-- bbook_right_sidebar_responsive -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-1952308982289269"
     data-ad-slot="5732385980"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div></section>
<section id="custom_html-31" class="widget_text widget widget_custom_html"><div class="widget_text widget-wrap"><div class="textwidget custom-html-widget"><div data-type="ad" data-publisher="Beginnersbook.com" data-format="160x600" data-zone="ros" ></div></div></div></section>
<section id="custom_html-29" class="widget_text widget widget_custom_html"><div class="widget_text widget-wrap"><div class="textwidget custom-html-widget"><div data-type="ad" data-publisher="Beginnersbook.com" data-format="160x600" data-zone="ros" ></div></div></div></section>
</aside></div><aside class="sidebar sidebar-secondary widget-area" role="complementary" aria-label="Secondary Sidebar" itemscope itemtype="https://schema.org/WPSideBar"><section id="custom_html-17" class="widget_text widget widget_custom_html"><div class="widget_text widget-wrap"><h4 class="widget-title widgettitle">Exception Handling</h4>
<div class="textwidget custom-html-widget"><ul>
<li><a href="../../04/java-exception-handling/index.html">Exception handling</a></li> 
<li><a href="../../04/try-catch-in-java/index.html">try-catch block</a></li>
<li><a href="index.html">Multiple catch blocks</a></li>
<li><a href="../../04/nested-try-catch/index.html">nested try-catch</a></li> 
<li><a href="../../04/java-finally-block/index.html">finally block</a></li> 
<li><a href="../flow-in-try-catch-finally/index.html">Flow Control in try-catch-finally</a></li>
<li><a href="../../04/throw-in-java/index.html">throw keyword</a></li> 
<li><a href="../../04/java-throws/index.html">throws clause</a></li> 
<li><a href="../../04/difference-between-throw-and-throws-in-java/index.html">throw vs throws</a></li>  
 <li><a href="../../04/user-defined-exception-in-java/index.html">Custom Exception</a></li> 
<li><a href="../../04/java-checked-unchecked-exceptions-with-examples/index.html">Checked and Unchecked Exceptions</a></li> 
<li><a href="../../04/exception-handling-examples/index.html">Exception Examples</a></li> 
</ul>
<h4 class="widget-title">MORE ...</h4>
<ul>
<li><a href="../../../java-tutorial-for-beginners-with-examples/index.html">Java Tutorial</a></li>
<li><a href="../../04/oops-concepts/index.html">OOPs Concepts</a></li>
 	<li><a href="../../12/java-strings/index.html">Java String</a></li>
 	<li><a href="../../03/multithreading-in-java/index.html">Java Multithreading</a></li>
 	<li><a href="../../../java-io-tutorial-with-examples/index.html">Java I/O</a></li>
 	<li><a href="../../../2014/07/java-serialization/index.html">Java Serialization</a></li>
	<li><a href="../../../2014/08/java-regex-tutorial/index.html">Java Regex</a></li>
	<li><a href="../../../2015/06/java-awt-tutorial/index.html">Java AWT</a></li>
	<li><a href="../../../2015/07/java-swing-tutorial/index.html">Java Swing</a></li>
<li><a href="../../../2014/09/java-enum-examples/index.html">Java Enum</a></li>
<li><a href="../../../2014/09/java-annotations/index.html">Java Annotations</a></li>
</ul></div></div></section>
</aside></div><footer class="site-footer" itemscope itemtype="https://schema.org/WPFooter"><div class="wrap"><p>Copyright © 2012 – 2018 BeginnersBook - All Rights Reserved || <a href="../../../sitemap_index.xml" title="Sitemap">Sitemap</a></p></div></footer></div><script type="text/javascript" src="../../../highlighter/prettify.js"></script>
<script type="text/javascript" charset="utf-8">
jQuery(document).ready(function($) {
       $('pre').addClass("prettyprint");
       prettyPrint();
});
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','../../../../www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-35249844-1', 'auto');
  ga('send', 'pageview');

</script>
<script type='text/javascript'>
function _dmBootstrap(file) {
    var _dma = document.createElement('script');
    _dma.type = 'text/javascript';
    _dma.async = true;
    _dma.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + file;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(_dma);
}
function _dmFollowup(file) { if (typeof DMAds === 'undefined') _dmBootstrap('cdn2.DeveloperMedia.com/a.min.html'); }
(function () { _dmBootstrap('cdn1.DeveloperMedia.com/a.min.html'); setTimeout(_dmFollowup, 2000); })();
</script><script type='text/javascript' src='../../../wp-includes/js/comment-reply.min55fe.js?ver=4.9.5'></script>
<script type='text/javascript' src='../../../wp-includes/js/wp-embed.min55fe.js?ver=4.9.5'></script>
<script async="async" type='text/javascript' src='../../../wp-content/plugins/akismet/_inc/formfa0c.js?ver=4.0.3'></script>
</body>
<!-- Mirrored from beginnersbook.com/2013/05/catch-multiple-exceptions/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 16 Apr 2018 05:22:19 GMT -->
</html>
